// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.tencent.polaris.client.pb;

public final class ClientProto {
  private ClientProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClientOrBuilder extends
      // @@protoc_insertion_point(interface_extends:v1.Client)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.StringValue host = 1;</code>
     * @return Whether the host field is set.
     */
    boolean hasHost();
    /**
     * <code>.google.protobuf.StringValue host = 1;</code>
     * @return The host.
     */
    com.google.protobuf.StringValue getHost();
    /**
     * <code>.google.protobuf.StringValue host = 1;</code>
     */
    com.google.protobuf.StringValueOrBuilder getHostOrBuilder();

    /**
     * <code>.v1.Client.ClientType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.v1.Client.ClientType type = 2;</code>
     * @return The type.
     */
    com.tencent.polaris.client.pb.ClientProto.Client.ClientType getType();

    /**
     * <code>.google.protobuf.StringValue version = 3;</code>
     * @return Whether the version field is set.
     */
    boolean hasVersion();
    /**
     * <code>.google.protobuf.StringValue version = 3;</code>
     * @return The version.
     */
    com.google.protobuf.StringValue getVersion();
    /**
     * <code>.google.protobuf.StringValue version = 3;</code>
     */
    com.google.protobuf.StringValueOrBuilder getVersionOrBuilder();

    /**
     * <code>.v1.Location location = 4;</code>
     * @return Whether the location field is set.
     */
    boolean hasLocation();
    /**
     * <code>.v1.Location location = 4;</code>
     * @return The location.
     */
    com.tencent.polaris.client.pb.ModelProto.Location getLocation();
    /**
     * <code>.v1.Location location = 4;</code>
     */
    com.tencent.polaris.client.pb.ModelProto.LocationOrBuilder getLocationOrBuilder();
  }
  /**
   * Protobuf type {@code v1.Client}
   */
  public static final class Client extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:v1.Client)
      ClientOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Client.newBuilder() to construct.
    private Client(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Client() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Client();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Client(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (host_ != null) {
                subBuilder = host_.toBuilder();
              }
              host_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(host_);
                host_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 26: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (version_ != null) {
                subBuilder = version_.toBuilder();
              }
              version_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(version_);
                version_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.tencent.polaris.client.pb.ModelProto.Location.Builder subBuilder = null;
              if (location_ != null) {
                subBuilder = location_.toBuilder();
              }
              location_ = input.readMessage(com.tencent.polaris.client.pb.ModelProto.Location.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(location_);
                location_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.polaris.client.pb.ClientProto.internal_static_v1_Client_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.polaris.client.pb.ClientProto.internal_static_v1_Client_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.polaris.client.pb.ClientProto.Client.class, com.tencent.polaris.client.pb.ClientProto.Client.Builder.class);
    }

    /**
     * Protobuf enum {@code v1.Client.ClientType}
     */
    public enum ClientType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>SDK = 1;</code>
       */
      SDK(1),
      /**
       * <code>AGENT = 2;</code>
       */
      AGENT(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>SDK = 1;</code>
       */
      public static final int SDK_VALUE = 1;
      /**
       * <code>AGENT = 2;</code>
       */
      public static final int AGENT_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ClientType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ClientType forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return SDK;
          case 2: return AGENT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ClientType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ClientType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ClientType>() {
              public ClientType findValueByNumber(int number) {
                return ClientType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tencent.polaris.client.pb.ClientProto.Client.getDescriptor().getEnumTypes().get(0);
      }

      private static final ClientType[] VALUES = values();

      public static ClientType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ClientType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:v1.Client.ClientType)
    }

    public static final int HOST_FIELD_NUMBER = 1;
    private com.google.protobuf.StringValue host_;
    /**
     * <code>.google.protobuf.StringValue host = 1;</code>
     * @return Whether the host field is set.
     */
    @java.lang.Override
    public boolean hasHost() {
      return host_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue host = 1;</code>
     * @return The host.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getHost() {
      return host_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : host_;
    }
    /**
     * <code>.google.protobuf.StringValue host = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getHostOrBuilder() {
      return getHost();
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.v1.Client.ClientType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.v1.Client.ClientType type = 2;</code>
     * @return The type.
     */
    @java.lang.Override public com.tencent.polaris.client.pb.ClientProto.Client.ClientType getType() {
      @SuppressWarnings("deprecation")
      com.tencent.polaris.client.pb.ClientProto.Client.ClientType result = com.tencent.polaris.client.pb.ClientProto.Client.ClientType.valueOf(type_);
      return result == null ? com.tencent.polaris.client.pb.ClientProto.Client.ClientType.UNRECOGNIZED : result;
    }

    public static final int VERSION_FIELD_NUMBER = 3;
    private com.google.protobuf.StringValue version_;
    /**
     * <code>.google.protobuf.StringValue version = 3;</code>
     * @return Whether the version field is set.
     */
    @java.lang.Override
    public boolean hasVersion() {
      return version_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue version = 3;</code>
     * @return The version.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getVersion() {
      return version_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : version_;
    }
    /**
     * <code>.google.protobuf.StringValue version = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getVersionOrBuilder() {
      return getVersion();
    }

    public static final int LOCATION_FIELD_NUMBER = 4;
    private com.tencent.polaris.client.pb.ModelProto.Location location_;
    /**
     * <code>.v1.Location location = 4;</code>
     * @return Whether the location field is set.
     */
    @java.lang.Override
    public boolean hasLocation() {
      return location_ != null;
    }
    /**
     * <code>.v1.Location location = 4;</code>
     * @return The location.
     */
    @java.lang.Override
    public com.tencent.polaris.client.pb.ModelProto.Location getLocation() {
      return location_ == null ? com.tencent.polaris.client.pb.ModelProto.Location.getDefaultInstance() : location_;
    }
    /**
     * <code>.v1.Location location = 4;</code>
     */
    @java.lang.Override
    public com.tencent.polaris.client.pb.ModelProto.LocationOrBuilder getLocationOrBuilder() {
      return getLocation();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (host_ != null) {
        output.writeMessage(1, getHost());
      }
      if (type_ != com.tencent.polaris.client.pb.ClientProto.Client.ClientType.UNKNOWN.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (version_ != null) {
        output.writeMessage(3, getVersion());
      }
      if (location_ != null) {
        output.writeMessage(4, getLocation());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (host_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHost());
      }
      if (type_ != com.tencent.polaris.client.pb.ClientProto.Client.ClientType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (version_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getVersion());
      }
      if (location_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getLocation());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tencent.polaris.client.pb.ClientProto.Client)) {
        return super.equals(obj);
      }
      com.tencent.polaris.client.pb.ClientProto.Client other = (com.tencent.polaris.client.pb.ClientProto.Client) obj;

      if (hasHost() != other.hasHost()) return false;
      if (hasHost()) {
        if (!getHost()
            .equals(other.getHost())) return false;
      }
      if (type_ != other.type_) return false;
      if (hasVersion() != other.hasVersion()) return false;
      if (hasVersion()) {
        if (!getVersion()
            .equals(other.getVersion())) return false;
      }
      if (hasLocation() != other.hasLocation()) return false;
      if (hasLocation()) {
        if (!getLocation()
            .equals(other.getLocation())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHost()) {
        hash = (37 * hash) + HOST_FIELD_NUMBER;
        hash = (53 * hash) + getHost().hashCode();
      }
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion().hashCode();
      }
      if (hasLocation()) {
        hash = (37 * hash) + LOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getLocation().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tencent.polaris.client.pb.ClientProto.Client parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.polaris.client.pb.ClientProto.Client parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.polaris.client.pb.ClientProto.Client parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.polaris.client.pb.ClientProto.Client parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.polaris.client.pb.ClientProto.Client parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.polaris.client.pb.ClientProto.Client parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.polaris.client.pb.ClientProto.Client parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.polaris.client.pb.ClientProto.Client parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.polaris.client.pb.ClientProto.Client parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tencent.polaris.client.pb.ClientProto.Client parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.polaris.client.pb.ClientProto.Client parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.polaris.client.pb.ClientProto.Client parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tencent.polaris.client.pb.ClientProto.Client prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code v1.Client}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:v1.Client)
        com.tencent.polaris.client.pb.ClientProto.ClientOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.polaris.client.pb.ClientProto.internal_static_v1_Client_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.polaris.client.pb.ClientProto.internal_static_v1_Client_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.polaris.client.pb.ClientProto.Client.class, com.tencent.polaris.client.pb.ClientProto.Client.Builder.class);
      }

      // Construct using com.tencent.polaris.client.pb.ClientProto.Client.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (hostBuilder_ == null) {
          host_ = null;
        } else {
          host_ = null;
          hostBuilder_ = null;
        }
        type_ = 0;

        if (versionBuilder_ == null) {
          version_ = null;
        } else {
          version_ = null;
          versionBuilder_ = null;
        }
        if (locationBuilder_ == null) {
          location_ = null;
        } else {
          location_ = null;
          locationBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.polaris.client.pb.ClientProto.internal_static_v1_Client_descriptor;
      }

      @java.lang.Override
      public com.tencent.polaris.client.pb.ClientProto.Client getDefaultInstanceForType() {
        return com.tencent.polaris.client.pb.ClientProto.Client.getDefaultInstance();
      }

      @java.lang.Override
      public com.tencent.polaris.client.pb.ClientProto.Client build() {
        com.tencent.polaris.client.pb.ClientProto.Client result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tencent.polaris.client.pb.ClientProto.Client buildPartial() {
        com.tencent.polaris.client.pb.ClientProto.Client result = new com.tencent.polaris.client.pb.ClientProto.Client(this);
        if (hostBuilder_ == null) {
          result.host_ = host_;
        } else {
          result.host_ = hostBuilder_.build();
        }
        result.type_ = type_;
        if (versionBuilder_ == null) {
          result.version_ = version_;
        } else {
          result.version_ = versionBuilder_.build();
        }
        if (locationBuilder_ == null) {
          result.location_ = location_;
        } else {
          result.location_ = locationBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.polaris.client.pb.ClientProto.Client) {
          return mergeFrom((com.tencent.polaris.client.pb.ClientProto.Client)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.polaris.client.pb.ClientProto.Client other) {
        if (other == com.tencent.polaris.client.pb.ClientProto.Client.getDefaultInstance()) return this;
        if (other.hasHost()) {
          mergeHost(other.getHost());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasVersion()) {
          mergeVersion(other.getVersion());
        }
        if (other.hasLocation()) {
          mergeLocation(other.getLocation());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tencent.polaris.client.pb.ClientProto.Client parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tencent.polaris.client.pb.ClientProto.Client) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.StringValue host_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> hostBuilder_;
      /**
       * <code>.google.protobuf.StringValue host = 1;</code>
       * @return Whether the host field is set.
       */
      public boolean hasHost() {
        return hostBuilder_ != null || host_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue host = 1;</code>
       * @return The host.
       */
      public com.google.protobuf.StringValue getHost() {
        if (hostBuilder_ == null) {
          return host_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : host_;
        } else {
          return hostBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue host = 1;</code>
       */
      public Builder setHost(com.google.protobuf.StringValue value) {
        if (hostBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          host_ = value;
          onChanged();
        } else {
          hostBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue host = 1;</code>
       */
      public Builder setHost(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (hostBuilder_ == null) {
          host_ = builderForValue.build();
          onChanged();
        } else {
          hostBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue host = 1;</code>
       */
      public Builder mergeHost(com.google.protobuf.StringValue value) {
        if (hostBuilder_ == null) {
          if (host_ != null) {
            host_ =
              com.google.protobuf.StringValue.newBuilder(host_).mergeFrom(value).buildPartial();
          } else {
            host_ = value;
          }
          onChanged();
        } else {
          hostBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue host = 1;</code>
       */
      public Builder clearHost() {
        if (hostBuilder_ == null) {
          host_ = null;
          onChanged();
        } else {
          host_ = null;
          hostBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue host = 1;</code>
       */
      public com.google.protobuf.StringValue.Builder getHostBuilder() {
        
        onChanged();
        return getHostFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue host = 1;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getHostOrBuilder() {
        if (hostBuilder_ != null) {
          return hostBuilder_.getMessageOrBuilder();
        } else {
          return host_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : host_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue host = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getHostFieldBuilder() {
        if (hostBuilder_ == null) {
          hostBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getHost(),
                  getParentForChildren(),
                  isClean());
          host_ = null;
        }
        return hostBuilder_;
      }

      private int type_ = 0;
      /**
       * <code>.v1.Client.ClientType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.v1.Client.ClientType type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.v1.Client.ClientType type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.tencent.polaris.client.pb.ClientProto.Client.ClientType getType() {
        @SuppressWarnings("deprecation")
        com.tencent.polaris.client.pb.ClientProto.Client.ClientType result = com.tencent.polaris.client.pb.ClientProto.Client.ClientType.valueOf(type_);
        return result == null ? com.tencent.polaris.client.pb.ClientProto.Client.ClientType.UNRECOGNIZED : result;
      }
      /**
       * <code>.v1.Client.ClientType type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.tencent.polaris.client.pb.ClientProto.Client.ClientType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.v1.Client.ClientType type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.StringValue version_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> versionBuilder_;
      /**
       * <code>.google.protobuf.StringValue version = 3;</code>
       * @return Whether the version field is set.
       */
      public boolean hasVersion() {
        return versionBuilder_ != null || version_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue version = 3;</code>
       * @return The version.
       */
      public com.google.protobuf.StringValue getVersion() {
        if (versionBuilder_ == null) {
          return version_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : version_;
        } else {
          return versionBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue version = 3;</code>
       */
      public Builder setVersion(com.google.protobuf.StringValue value) {
        if (versionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          version_ = value;
          onChanged();
        } else {
          versionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue version = 3;</code>
       */
      public Builder setVersion(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (versionBuilder_ == null) {
          version_ = builderForValue.build();
          onChanged();
        } else {
          versionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue version = 3;</code>
       */
      public Builder mergeVersion(com.google.protobuf.StringValue value) {
        if (versionBuilder_ == null) {
          if (version_ != null) {
            version_ =
              com.google.protobuf.StringValue.newBuilder(version_).mergeFrom(value).buildPartial();
          } else {
            version_ = value;
          }
          onChanged();
        } else {
          versionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue version = 3;</code>
       */
      public Builder clearVersion() {
        if (versionBuilder_ == null) {
          version_ = null;
          onChanged();
        } else {
          version_ = null;
          versionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue version = 3;</code>
       */
      public com.google.protobuf.StringValue.Builder getVersionBuilder() {
        
        onChanged();
        return getVersionFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue version = 3;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getVersionOrBuilder() {
        if (versionBuilder_ != null) {
          return versionBuilder_.getMessageOrBuilder();
        } else {
          return version_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : version_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue version = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getVersionFieldBuilder() {
        if (versionBuilder_ == null) {
          versionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getVersion(),
                  getParentForChildren(),
                  isClean());
          version_ = null;
        }
        return versionBuilder_;
      }

      private com.tencent.polaris.client.pb.ModelProto.Location location_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tencent.polaris.client.pb.ModelProto.Location, com.tencent.polaris.client.pb.ModelProto.Location.Builder, com.tencent.polaris.client.pb.ModelProto.LocationOrBuilder> locationBuilder_;
      /**
       * <code>.v1.Location location = 4;</code>
       * @return Whether the location field is set.
       */
      public boolean hasLocation() {
        return locationBuilder_ != null || location_ != null;
      }
      /**
       * <code>.v1.Location location = 4;</code>
       * @return The location.
       */
      public com.tencent.polaris.client.pb.ModelProto.Location getLocation() {
        if (locationBuilder_ == null) {
          return location_ == null ? com.tencent.polaris.client.pb.ModelProto.Location.getDefaultInstance() : location_;
        } else {
          return locationBuilder_.getMessage();
        }
      }
      /**
       * <code>.v1.Location location = 4;</code>
       */
      public Builder setLocation(com.tencent.polaris.client.pb.ModelProto.Location value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          location_ = value;
          onChanged();
        } else {
          locationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.v1.Location location = 4;</code>
       */
      public Builder setLocation(
          com.tencent.polaris.client.pb.ModelProto.Location.Builder builderForValue) {
        if (locationBuilder_ == null) {
          location_ = builderForValue.build();
          onChanged();
        } else {
          locationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.v1.Location location = 4;</code>
       */
      public Builder mergeLocation(com.tencent.polaris.client.pb.ModelProto.Location value) {
        if (locationBuilder_ == null) {
          if (location_ != null) {
            location_ =
              com.tencent.polaris.client.pb.ModelProto.Location.newBuilder(location_).mergeFrom(value).buildPartial();
          } else {
            location_ = value;
          }
          onChanged();
        } else {
          locationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.v1.Location location = 4;</code>
       */
      public Builder clearLocation() {
        if (locationBuilder_ == null) {
          location_ = null;
          onChanged();
        } else {
          location_ = null;
          locationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.v1.Location location = 4;</code>
       */
      public com.tencent.polaris.client.pb.ModelProto.Location.Builder getLocationBuilder() {
        
        onChanged();
        return getLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>.v1.Location location = 4;</code>
       */
      public com.tencent.polaris.client.pb.ModelProto.LocationOrBuilder getLocationOrBuilder() {
        if (locationBuilder_ != null) {
          return locationBuilder_.getMessageOrBuilder();
        } else {
          return location_ == null ?
              com.tencent.polaris.client.pb.ModelProto.Location.getDefaultInstance() : location_;
        }
      }
      /**
       * <code>.v1.Location location = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tencent.polaris.client.pb.ModelProto.Location, com.tencent.polaris.client.pb.ModelProto.Location.Builder, com.tencent.polaris.client.pb.ModelProto.LocationOrBuilder> 
          getLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.tencent.polaris.client.pb.ModelProto.Location, com.tencent.polaris.client.pb.ModelProto.Location.Builder, com.tencent.polaris.client.pb.ModelProto.LocationOrBuilder>(
                  getLocation(),
                  getParentForChildren(),
                  isClean());
          location_ = null;
        }
        return locationBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:v1.Client)
    }

    // @@protoc_insertion_point(class_scope:v1.Client)
    private static final com.tencent.polaris.client.pb.ClientProto.Client DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tencent.polaris.client.pb.ClientProto.Client();
    }

    public static com.tencent.polaris.client.pb.ClientProto.Client getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Client>
        PARSER = new com.google.protobuf.AbstractParser<Client>() {
      @java.lang.Override
      public Client parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Client(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Client> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Client> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tencent.polaris.client.pb.ClientProto.Client getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v1_Client_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v1_Client_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014client.proto\022\002v1\032\036google/protobuf/wrap" +
      "pers.proto\032\013model.proto\"\327\001\n\006Client\022*\n\004ho" +
      "st\030\001 \001(\0132\034.google.protobuf.StringValue\022#" +
      "\n\004type\030\002 \001(\0162\025.v1.Client.ClientType\022-\n\007v" +
      "ersion\030\003 \001(\0132\034.google.protobuf.StringVal" +
      "ue\022\036\n\010location\030\004 \001(\0132\014.v1.Location\"-\n\nCl" +
      "ientType\022\013\n\007UNKNOWN\020\000\022\007\n\003SDK\020\001\022\t\n\005AGENT\020" +
      "\002B,\n\035com.tencent.polaris.client.pbB\013Clie" +
      "ntProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.tencent.polaris.client.pb.ModelProto.getDescriptor(),
        });
    internal_static_v1_Client_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_v1_Client_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v1_Client_descriptor,
        new java.lang.String[] { "Host", "Type", "Version", "Location", });
    com.google.protobuf.WrappersProto.getDescriptor();
    com.tencent.polaris.client.pb.ModelProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
