// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.tencent.polaris.client.pb;

public final class ModelProto {
  private ModelProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:v1.Location)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.StringValue region = 1;</code>
     * @return Whether the region field is set.
     */
    boolean hasRegion();
    /**
     * <code>.google.protobuf.StringValue region = 1;</code>
     * @return The region.
     */
    com.google.protobuf.StringValue getRegion();
    /**
     * <code>.google.protobuf.StringValue region = 1;</code>
     */
    com.google.protobuf.StringValueOrBuilder getRegionOrBuilder();

    /**
     * <code>.google.protobuf.StringValue zone = 2;</code>
     * @return Whether the zone field is set.
     */
    boolean hasZone();
    /**
     * <code>.google.protobuf.StringValue zone = 2;</code>
     * @return The zone.
     */
    com.google.protobuf.StringValue getZone();
    /**
     * <code>.google.protobuf.StringValue zone = 2;</code>
     */
    com.google.protobuf.StringValueOrBuilder getZoneOrBuilder();

    /**
     * <code>.google.protobuf.StringValue campus = 3;</code>
     * @return Whether the campus field is set.
     */
    boolean hasCampus();
    /**
     * <code>.google.protobuf.StringValue campus = 3;</code>
     * @return The campus.
     */
    com.google.protobuf.StringValue getCampus();
    /**
     * <code>.google.protobuf.StringValue campus = 3;</code>
     */
    com.google.protobuf.StringValueOrBuilder getCampusOrBuilder();
  }
  /**
   * Protobuf type {@code v1.Location}
   */
  public static final class Location extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:v1.Location)
      LocationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Location.newBuilder() to construct.
    private Location(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Location() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Location();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Location(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (region_ != null) {
                subBuilder = region_.toBuilder();
              }
              region_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(region_);
                region_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (zone_ != null) {
                subBuilder = zone_.toBuilder();
              }
              zone_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(zone_);
                zone_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (campus_ != null) {
                subBuilder = campus_.toBuilder();
              }
              campus_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(campus_);
                campus_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.polaris.client.pb.ModelProto.internal_static_v1_Location_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.polaris.client.pb.ModelProto.internal_static_v1_Location_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.polaris.client.pb.ModelProto.Location.class, com.tencent.polaris.client.pb.ModelProto.Location.Builder.class);
    }

    public static final int REGION_FIELD_NUMBER = 1;
    private com.google.protobuf.StringValue region_;
    /**
     * <code>.google.protobuf.StringValue region = 1;</code>
     * @return Whether the region field is set.
     */
    @java.lang.Override
    public boolean hasRegion() {
      return region_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue region = 1;</code>
     * @return The region.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getRegion() {
      return region_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : region_;
    }
    /**
     * <code>.google.protobuf.StringValue region = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getRegionOrBuilder() {
      return getRegion();
    }

    public static final int ZONE_FIELD_NUMBER = 2;
    private com.google.protobuf.StringValue zone_;
    /**
     * <code>.google.protobuf.StringValue zone = 2;</code>
     * @return Whether the zone field is set.
     */
    @java.lang.Override
    public boolean hasZone() {
      return zone_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue zone = 2;</code>
     * @return The zone.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getZone() {
      return zone_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : zone_;
    }
    /**
     * <code>.google.protobuf.StringValue zone = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getZoneOrBuilder() {
      return getZone();
    }

    public static final int CAMPUS_FIELD_NUMBER = 3;
    private com.google.protobuf.StringValue campus_;
    /**
     * <code>.google.protobuf.StringValue campus = 3;</code>
     * @return Whether the campus field is set.
     */
    @java.lang.Override
    public boolean hasCampus() {
      return campus_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue campus = 3;</code>
     * @return The campus.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getCampus() {
      return campus_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : campus_;
    }
    /**
     * <code>.google.protobuf.StringValue campus = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getCampusOrBuilder() {
      return getCampus();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (region_ != null) {
        output.writeMessage(1, getRegion());
      }
      if (zone_ != null) {
        output.writeMessage(2, getZone());
      }
      if (campus_ != null) {
        output.writeMessage(3, getCampus());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (region_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRegion());
      }
      if (zone_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getZone());
      }
      if (campus_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getCampus());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tencent.polaris.client.pb.ModelProto.Location)) {
        return super.equals(obj);
      }
      com.tencent.polaris.client.pb.ModelProto.Location other = (com.tencent.polaris.client.pb.ModelProto.Location) obj;

      if (hasRegion() != other.hasRegion()) return false;
      if (hasRegion()) {
        if (!getRegion()
            .equals(other.getRegion())) return false;
      }
      if (hasZone() != other.hasZone()) return false;
      if (hasZone()) {
        if (!getZone()
            .equals(other.getZone())) return false;
      }
      if (hasCampus() != other.hasCampus()) return false;
      if (hasCampus()) {
        if (!getCampus()
            .equals(other.getCampus())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRegion()) {
        hash = (37 * hash) + REGION_FIELD_NUMBER;
        hash = (53 * hash) + getRegion().hashCode();
      }
      if (hasZone()) {
        hash = (37 * hash) + ZONE_FIELD_NUMBER;
        hash = (53 * hash) + getZone().hashCode();
      }
      if (hasCampus()) {
        hash = (37 * hash) + CAMPUS_FIELD_NUMBER;
        hash = (53 * hash) + getCampus().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tencent.polaris.client.pb.ModelProto.Location parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.polaris.client.pb.ModelProto.Location parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.polaris.client.pb.ModelProto.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.polaris.client.pb.ModelProto.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.polaris.client.pb.ModelProto.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.polaris.client.pb.ModelProto.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.polaris.client.pb.ModelProto.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.polaris.client.pb.ModelProto.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.polaris.client.pb.ModelProto.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tencent.polaris.client.pb.ModelProto.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.polaris.client.pb.ModelProto.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.polaris.client.pb.ModelProto.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tencent.polaris.client.pb.ModelProto.Location prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code v1.Location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:v1.Location)
        com.tencent.polaris.client.pb.ModelProto.LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.polaris.client.pb.ModelProto.internal_static_v1_Location_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.polaris.client.pb.ModelProto.internal_static_v1_Location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.polaris.client.pb.ModelProto.Location.class, com.tencent.polaris.client.pb.ModelProto.Location.Builder.class);
      }

      // Construct using com.tencent.polaris.client.pb.ModelProto.Location.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (regionBuilder_ == null) {
          region_ = null;
        } else {
          region_ = null;
          regionBuilder_ = null;
        }
        if (zoneBuilder_ == null) {
          zone_ = null;
        } else {
          zone_ = null;
          zoneBuilder_ = null;
        }
        if (campusBuilder_ == null) {
          campus_ = null;
        } else {
          campus_ = null;
          campusBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.polaris.client.pb.ModelProto.internal_static_v1_Location_descriptor;
      }

      @java.lang.Override
      public com.tencent.polaris.client.pb.ModelProto.Location getDefaultInstanceForType() {
        return com.tencent.polaris.client.pb.ModelProto.Location.getDefaultInstance();
      }

      @java.lang.Override
      public com.tencent.polaris.client.pb.ModelProto.Location build() {
        com.tencent.polaris.client.pb.ModelProto.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tencent.polaris.client.pb.ModelProto.Location buildPartial() {
        com.tencent.polaris.client.pb.ModelProto.Location result = new com.tencent.polaris.client.pb.ModelProto.Location(this);
        if (regionBuilder_ == null) {
          result.region_ = region_;
        } else {
          result.region_ = regionBuilder_.build();
        }
        if (zoneBuilder_ == null) {
          result.zone_ = zone_;
        } else {
          result.zone_ = zoneBuilder_.build();
        }
        if (campusBuilder_ == null) {
          result.campus_ = campus_;
        } else {
          result.campus_ = campusBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.polaris.client.pb.ModelProto.Location) {
          return mergeFrom((com.tencent.polaris.client.pb.ModelProto.Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.polaris.client.pb.ModelProto.Location other) {
        if (other == com.tencent.polaris.client.pb.ModelProto.Location.getDefaultInstance()) return this;
        if (other.hasRegion()) {
          mergeRegion(other.getRegion());
        }
        if (other.hasZone()) {
          mergeZone(other.getZone());
        }
        if (other.hasCampus()) {
          mergeCampus(other.getCampus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tencent.polaris.client.pb.ModelProto.Location parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tencent.polaris.client.pb.ModelProto.Location) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.StringValue region_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> regionBuilder_;
      /**
       * <code>.google.protobuf.StringValue region = 1;</code>
       * @return Whether the region field is set.
       */
      public boolean hasRegion() {
        return regionBuilder_ != null || region_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue region = 1;</code>
       * @return The region.
       */
      public com.google.protobuf.StringValue getRegion() {
        if (regionBuilder_ == null) {
          return region_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : region_;
        } else {
          return regionBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue region = 1;</code>
       */
      public Builder setRegion(com.google.protobuf.StringValue value) {
        if (regionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          region_ = value;
          onChanged();
        } else {
          regionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue region = 1;</code>
       */
      public Builder setRegion(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (regionBuilder_ == null) {
          region_ = builderForValue.build();
          onChanged();
        } else {
          regionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue region = 1;</code>
       */
      public Builder mergeRegion(com.google.protobuf.StringValue value) {
        if (regionBuilder_ == null) {
          if (region_ != null) {
            region_ =
              com.google.protobuf.StringValue.newBuilder(region_).mergeFrom(value).buildPartial();
          } else {
            region_ = value;
          }
          onChanged();
        } else {
          regionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue region = 1;</code>
       */
      public Builder clearRegion() {
        if (regionBuilder_ == null) {
          region_ = null;
          onChanged();
        } else {
          region_ = null;
          regionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue region = 1;</code>
       */
      public com.google.protobuf.StringValue.Builder getRegionBuilder() {
        
        onChanged();
        return getRegionFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue region = 1;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getRegionOrBuilder() {
        if (regionBuilder_ != null) {
          return regionBuilder_.getMessageOrBuilder();
        } else {
          return region_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : region_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue region = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getRegionFieldBuilder() {
        if (regionBuilder_ == null) {
          regionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getRegion(),
                  getParentForChildren(),
                  isClean());
          region_ = null;
        }
        return regionBuilder_;
      }

      private com.google.protobuf.StringValue zone_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> zoneBuilder_;
      /**
       * <code>.google.protobuf.StringValue zone = 2;</code>
       * @return Whether the zone field is set.
       */
      public boolean hasZone() {
        return zoneBuilder_ != null || zone_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue zone = 2;</code>
       * @return The zone.
       */
      public com.google.protobuf.StringValue getZone() {
        if (zoneBuilder_ == null) {
          return zone_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : zone_;
        } else {
          return zoneBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue zone = 2;</code>
       */
      public Builder setZone(com.google.protobuf.StringValue value) {
        if (zoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          zone_ = value;
          onChanged();
        } else {
          zoneBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue zone = 2;</code>
       */
      public Builder setZone(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (zoneBuilder_ == null) {
          zone_ = builderForValue.build();
          onChanged();
        } else {
          zoneBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue zone = 2;</code>
       */
      public Builder mergeZone(com.google.protobuf.StringValue value) {
        if (zoneBuilder_ == null) {
          if (zone_ != null) {
            zone_ =
              com.google.protobuf.StringValue.newBuilder(zone_).mergeFrom(value).buildPartial();
          } else {
            zone_ = value;
          }
          onChanged();
        } else {
          zoneBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue zone = 2;</code>
       */
      public Builder clearZone() {
        if (zoneBuilder_ == null) {
          zone_ = null;
          onChanged();
        } else {
          zone_ = null;
          zoneBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue zone = 2;</code>
       */
      public com.google.protobuf.StringValue.Builder getZoneBuilder() {
        
        onChanged();
        return getZoneFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue zone = 2;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getZoneOrBuilder() {
        if (zoneBuilder_ != null) {
          return zoneBuilder_.getMessageOrBuilder();
        } else {
          return zone_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : zone_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue zone = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getZoneFieldBuilder() {
        if (zoneBuilder_ == null) {
          zoneBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getZone(),
                  getParentForChildren(),
                  isClean());
          zone_ = null;
        }
        return zoneBuilder_;
      }

      private com.google.protobuf.StringValue campus_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> campusBuilder_;
      /**
       * <code>.google.protobuf.StringValue campus = 3;</code>
       * @return Whether the campus field is set.
       */
      public boolean hasCampus() {
        return campusBuilder_ != null || campus_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue campus = 3;</code>
       * @return The campus.
       */
      public com.google.protobuf.StringValue getCampus() {
        if (campusBuilder_ == null) {
          return campus_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : campus_;
        } else {
          return campusBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue campus = 3;</code>
       */
      public Builder setCampus(com.google.protobuf.StringValue value) {
        if (campusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          campus_ = value;
          onChanged();
        } else {
          campusBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue campus = 3;</code>
       */
      public Builder setCampus(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (campusBuilder_ == null) {
          campus_ = builderForValue.build();
          onChanged();
        } else {
          campusBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue campus = 3;</code>
       */
      public Builder mergeCampus(com.google.protobuf.StringValue value) {
        if (campusBuilder_ == null) {
          if (campus_ != null) {
            campus_ =
              com.google.protobuf.StringValue.newBuilder(campus_).mergeFrom(value).buildPartial();
          } else {
            campus_ = value;
          }
          onChanged();
        } else {
          campusBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue campus = 3;</code>
       */
      public Builder clearCampus() {
        if (campusBuilder_ == null) {
          campus_ = null;
          onChanged();
        } else {
          campus_ = null;
          campusBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue campus = 3;</code>
       */
      public com.google.protobuf.StringValue.Builder getCampusBuilder() {
        
        onChanged();
        return getCampusFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue campus = 3;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getCampusOrBuilder() {
        if (campusBuilder_ != null) {
          return campusBuilder_.getMessageOrBuilder();
        } else {
          return campus_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : campus_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue campus = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getCampusFieldBuilder() {
        if (campusBuilder_ == null) {
          campusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getCampus(),
                  getParentForChildren(),
                  isClean());
          campus_ = null;
        }
        return campusBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:v1.Location)
    }

    // @@protoc_insertion_point(class_scope:v1.Location)
    private static final com.tencent.polaris.client.pb.ModelProto.Location DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tencent.polaris.client.pb.ModelProto.Location();
    }

    public static com.tencent.polaris.client.pb.ModelProto.Location getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Location>
        PARSER = new com.google.protobuf.AbstractParser<Location>() {
      @java.lang.Override
      public Location parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Location(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Location> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Location> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tencent.polaris.client.pb.ModelProto.Location getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MatchStringOrBuilder extends
      // @@protoc_insertion_point(interface_extends:v1.MatchString)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.v1.MatchString.MatchStringType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.v1.MatchString.MatchStringType type = 1;</code>
     * @return The type.
     */
    com.tencent.polaris.client.pb.ModelProto.MatchString.MatchStringType getType();

    /**
     * <code>.google.protobuf.StringValue value = 2;</code>
     * @return Whether the value field is set.
     */
    boolean hasValue();
    /**
     * <code>.google.protobuf.StringValue value = 2;</code>
     * @return The value.
     */
    com.google.protobuf.StringValue getValue();
    /**
     * <code>.google.protobuf.StringValue value = 2;</code>
     */
    com.google.protobuf.StringValueOrBuilder getValueOrBuilder();

    /**
     * <code>.v1.MatchString.ValueType value_type = 3;</code>
     * @return The enum numeric value on the wire for valueType.
     */
    int getValueTypeValue();
    /**
     * <code>.v1.MatchString.ValueType value_type = 3;</code>
     * @return The valueType.
     */
    com.tencent.polaris.client.pb.ModelProto.MatchString.ValueType getValueType();
  }
  /**
   * Protobuf type {@code v1.MatchString}
   */
  public static final class MatchString extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:v1.MatchString)
      MatchStringOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MatchString.newBuilder() to construct.
    private MatchString(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MatchString() {
      type_ = 0;
      valueType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MatchString();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MatchString(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (value_ != null) {
                subBuilder = value_.toBuilder();
              }
              value_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(value_);
                value_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              valueType_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.polaris.client.pb.ModelProto.internal_static_v1_MatchString_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.polaris.client.pb.ModelProto.internal_static_v1_MatchString_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.polaris.client.pb.ModelProto.MatchString.class, com.tencent.polaris.client.pb.ModelProto.MatchString.Builder.class);
    }

    /**
     * Protobuf enum {@code v1.MatchString.MatchStringType}
     */
    public enum MatchStringType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>EXACT = 0;</code>
       */
      EXACT(0),
      /**
       * <code>REGEX = 1;</code>
       */
      REGEX(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>EXACT = 0;</code>
       */
      public static final int EXACT_VALUE = 0;
      /**
       * <code>REGEX = 1;</code>
       */
      public static final int REGEX_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MatchStringType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MatchStringType forNumber(int value) {
        switch (value) {
          case 0: return EXACT;
          case 1: return REGEX;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MatchStringType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MatchStringType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MatchStringType>() {
              public MatchStringType findValueByNumber(int number) {
                return MatchStringType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tencent.polaris.client.pb.ModelProto.MatchString.getDescriptor().getEnumTypes().get(0);
      }

      private static final MatchStringType[] VALUES = values();

      public static MatchStringType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MatchStringType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:v1.MatchString.MatchStringType)
    }

    /**
     * Protobuf enum {@code v1.MatchString.ValueType}
     */
    public enum ValueType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TEXT = 0;</code>
       */
      TEXT(0),
      /**
       * <code>PARAMETER = 1;</code>
       */
      PARAMETER(1),
      /**
       * <code>VARIABLE = 2;</code>
       */
      VARIABLE(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>TEXT = 0;</code>
       */
      public static final int TEXT_VALUE = 0;
      /**
       * <code>PARAMETER = 1;</code>
       */
      public static final int PARAMETER_VALUE = 1;
      /**
       * <code>VARIABLE = 2;</code>
       */
      public static final int VARIABLE_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ValueType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ValueType forNumber(int value) {
        switch (value) {
          case 0: return TEXT;
          case 1: return PARAMETER;
          case 2: return VARIABLE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ValueType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ValueType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ValueType>() {
              public ValueType findValueByNumber(int number) {
                return ValueType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tencent.polaris.client.pb.ModelProto.MatchString.getDescriptor().getEnumTypes().get(1);
      }

      private static final ValueType[] VALUES = values();

      public static ValueType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ValueType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:v1.MatchString.ValueType)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.v1.MatchString.MatchStringType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.v1.MatchString.MatchStringType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public com.tencent.polaris.client.pb.ModelProto.MatchString.MatchStringType getType() {
      @SuppressWarnings("deprecation")
      com.tencent.polaris.client.pb.ModelProto.MatchString.MatchStringType result = com.tencent.polaris.client.pb.ModelProto.MatchString.MatchStringType.valueOf(type_);
      return result == null ? com.tencent.polaris.client.pb.ModelProto.MatchString.MatchStringType.UNRECOGNIZED : result;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.StringValue value_;
    /**
     * <code>.google.protobuf.StringValue value = 2;</code>
     * @return Whether the value field is set.
     */
    @java.lang.Override
    public boolean hasValue() {
      return value_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getValue() {
      return value_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : value_;
    }
    /**
     * <code>.google.protobuf.StringValue value = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getValueOrBuilder() {
      return getValue();
    }

    public static final int VALUE_TYPE_FIELD_NUMBER = 3;
    private int valueType_;
    /**
     * <code>.v1.MatchString.ValueType value_type = 3;</code>
     * @return The enum numeric value on the wire for valueType.
     */
    @java.lang.Override public int getValueTypeValue() {
      return valueType_;
    }
    /**
     * <code>.v1.MatchString.ValueType value_type = 3;</code>
     * @return The valueType.
     */
    @java.lang.Override public com.tencent.polaris.client.pb.ModelProto.MatchString.ValueType getValueType() {
      @SuppressWarnings("deprecation")
      com.tencent.polaris.client.pb.ModelProto.MatchString.ValueType result = com.tencent.polaris.client.pb.ModelProto.MatchString.ValueType.valueOf(valueType_);
      return result == null ? com.tencent.polaris.client.pb.ModelProto.MatchString.ValueType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.tencent.polaris.client.pb.ModelProto.MatchString.MatchStringType.EXACT.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (value_ != null) {
        output.writeMessage(2, getValue());
      }
      if (valueType_ != com.tencent.polaris.client.pb.ModelProto.MatchString.ValueType.TEXT.getNumber()) {
        output.writeEnum(3, valueType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.tencent.polaris.client.pb.ModelProto.MatchString.MatchStringType.EXACT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (value_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getValue());
      }
      if (valueType_ != com.tencent.polaris.client.pb.ModelProto.MatchString.ValueType.TEXT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, valueType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tencent.polaris.client.pb.ModelProto.MatchString)) {
        return super.equals(obj);
      }
      com.tencent.polaris.client.pb.ModelProto.MatchString other = (com.tencent.polaris.client.pb.ModelProto.MatchString) obj;

      if (type_ != other.type_) return false;
      if (hasValue() != other.hasValue()) return false;
      if (hasValue()) {
        if (!getValue()
            .equals(other.getValue())) return false;
      }
      if (valueType_ != other.valueType_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      hash = (37 * hash) + VALUE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + valueType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tencent.polaris.client.pb.ModelProto.MatchString parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.polaris.client.pb.ModelProto.MatchString parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.polaris.client.pb.ModelProto.MatchString parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.polaris.client.pb.ModelProto.MatchString parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.polaris.client.pb.ModelProto.MatchString parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.polaris.client.pb.ModelProto.MatchString parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.polaris.client.pb.ModelProto.MatchString parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.polaris.client.pb.ModelProto.MatchString parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.polaris.client.pb.ModelProto.MatchString parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tencent.polaris.client.pb.ModelProto.MatchString parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.polaris.client.pb.ModelProto.MatchString parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.polaris.client.pb.ModelProto.MatchString parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tencent.polaris.client.pb.ModelProto.MatchString prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code v1.MatchString}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:v1.MatchString)
        com.tencent.polaris.client.pb.ModelProto.MatchStringOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.polaris.client.pb.ModelProto.internal_static_v1_MatchString_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.polaris.client.pb.ModelProto.internal_static_v1_MatchString_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.polaris.client.pb.ModelProto.MatchString.class, com.tencent.polaris.client.pb.ModelProto.MatchString.Builder.class);
      }

      // Construct using com.tencent.polaris.client.pb.ModelProto.MatchString.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        if (valueBuilder_ == null) {
          value_ = null;
        } else {
          value_ = null;
          valueBuilder_ = null;
        }
        valueType_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.polaris.client.pb.ModelProto.internal_static_v1_MatchString_descriptor;
      }

      @java.lang.Override
      public com.tencent.polaris.client.pb.ModelProto.MatchString getDefaultInstanceForType() {
        return com.tencent.polaris.client.pb.ModelProto.MatchString.getDefaultInstance();
      }

      @java.lang.Override
      public com.tencent.polaris.client.pb.ModelProto.MatchString build() {
        com.tencent.polaris.client.pb.ModelProto.MatchString result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tencent.polaris.client.pb.ModelProto.MatchString buildPartial() {
        com.tencent.polaris.client.pb.ModelProto.MatchString result = new com.tencent.polaris.client.pb.ModelProto.MatchString(this);
        result.type_ = type_;
        if (valueBuilder_ == null) {
          result.value_ = value_;
        } else {
          result.value_ = valueBuilder_.build();
        }
        result.valueType_ = valueType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.polaris.client.pb.ModelProto.MatchString) {
          return mergeFrom((com.tencent.polaris.client.pb.ModelProto.MatchString)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.polaris.client.pb.ModelProto.MatchString other) {
        if (other == com.tencent.polaris.client.pb.ModelProto.MatchString.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasValue()) {
          mergeValue(other.getValue());
        }
        if (other.valueType_ != 0) {
          setValueTypeValue(other.getValueTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tencent.polaris.client.pb.ModelProto.MatchString parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tencent.polaris.client.pb.ModelProto.MatchString) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.v1.MatchString.MatchStringType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.v1.MatchString.MatchStringType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.v1.MatchString.MatchStringType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.tencent.polaris.client.pb.ModelProto.MatchString.MatchStringType getType() {
        @SuppressWarnings("deprecation")
        com.tencent.polaris.client.pb.ModelProto.MatchString.MatchStringType result = com.tencent.polaris.client.pb.ModelProto.MatchString.MatchStringType.valueOf(type_);
        return result == null ? com.tencent.polaris.client.pb.ModelProto.MatchString.MatchStringType.UNRECOGNIZED : result;
      }
      /**
       * <code>.v1.MatchString.MatchStringType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.tencent.polaris.client.pb.ModelProto.MatchString.MatchStringType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.v1.MatchString.MatchStringType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.StringValue value_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> valueBuilder_;
      /**
       * <code>.google.protobuf.StringValue value = 2;</code>
       * @return Whether the value field is set.
       */
      public boolean hasValue() {
        return valueBuilder_ != null || value_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue value = 2;</code>
       * @return The value.
       */
      public com.google.protobuf.StringValue getValue() {
        if (valueBuilder_ == null) {
          return value_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : value_;
        } else {
          return valueBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue value = 2;</code>
       */
      public Builder setValue(com.google.protobuf.StringValue value) {
        if (valueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
          onChanged();
        } else {
          valueBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue value = 2;</code>
       */
      public Builder setValue(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (valueBuilder_ == null) {
          value_ = builderForValue.build();
          onChanged();
        } else {
          valueBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue value = 2;</code>
       */
      public Builder mergeValue(com.google.protobuf.StringValue value) {
        if (valueBuilder_ == null) {
          if (value_ != null) {
            value_ =
              com.google.protobuf.StringValue.newBuilder(value_).mergeFrom(value).buildPartial();
          } else {
            value_ = value;
          }
          onChanged();
        } else {
          valueBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue value = 2;</code>
       */
      public Builder clearValue() {
        if (valueBuilder_ == null) {
          value_ = null;
          onChanged();
        } else {
          value_ = null;
          valueBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue value = 2;</code>
       */
      public com.google.protobuf.StringValue.Builder getValueBuilder() {
        
        onChanged();
        return getValueFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue value = 2;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getValueOrBuilder() {
        if (valueBuilder_ != null) {
          return valueBuilder_.getMessageOrBuilder();
        } else {
          return value_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : value_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue value = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getValueFieldBuilder() {
        if (valueBuilder_ == null) {
          valueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getValue(),
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        return valueBuilder_;
      }

      private int valueType_ = 0;
      /**
       * <code>.v1.MatchString.ValueType value_type = 3;</code>
       * @return The enum numeric value on the wire for valueType.
       */
      @java.lang.Override public int getValueTypeValue() {
        return valueType_;
      }
      /**
       * <code>.v1.MatchString.ValueType value_type = 3;</code>
       * @param value The enum numeric value on the wire for valueType to set.
       * @return This builder for chaining.
       */
      public Builder setValueTypeValue(int value) {
        
        valueType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.v1.MatchString.ValueType value_type = 3;</code>
       * @return The valueType.
       */
      @java.lang.Override
      public com.tencent.polaris.client.pb.ModelProto.MatchString.ValueType getValueType() {
        @SuppressWarnings("deprecation")
        com.tencent.polaris.client.pb.ModelProto.MatchString.ValueType result = com.tencent.polaris.client.pb.ModelProto.MatchString.ValueType.valueOf(valueType_);
        return result == null ? com.tencent.polaris.client.pb.ModelProto.MatchString.ValueType.UNRECOGNIZED : result;
      }
      /**
       * <code>.v1.MatchString.ValueType value_type = 3;</code>
       * @param value The valueType to set.
       * @return This builder for chaining.
       */
      public Builder setValueType(com.tencent.polaris.client.pb.ModelProto.MatchString.ValueType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        valueType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.v1.MatchString.ValueType value_type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearValueType() {
        
        valueType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:v1.MatchString)
    }

    // @@protoc_insertion_point(class_scope:v1.MatchString)
    private static final com.tencent.polaris.client.pb.ModelProto.MatchString DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tencent.polaris.client.pb.ModelProto.MatchString();
    }

    public static com.tencent.polaris.client.pb.ModelProto.MatchString getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MatchString>
        PARSER = new com.google.protobuf.AbstractParser<MatchString>() {
      @java.lang.Override
      public MatchString parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MatchString(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MatchString> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MatchString> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tencent.polaris.client.pb.ModelProto.MatchString getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v1_Location_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v1_Location_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v1_MatchString_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v1_MatchString_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013model.proto\022\002v1\032\036google/protobuf/wrapp" +
      "ers.proto\"\222\001\n\010Location\022,\n\006region\030\001 \001(\0132\034" +
      ".google.protobuf.StringValue\022*\n\004zone\030\002 \001" +
      "(\0132\034.google.protobuf.StringValue\022,\n\006camp" +
      "us\030\003 \001(\0132\034.google.protobuf.StringValue\"\365" +
      "\001\n\013MatchString\022-\n\004type\030\001 \001(\0162\037.v1.MatchS" +
      "tring.MatchStringType\022+\n\005value\030\002 \001(\0132\034.g" +
      "oogle.protobuf.StringValue\022-\n\nvalue_type" +
      "\030\003 \001(\0162\031.v1.MatchString.ValueType\"\'\n\017Mat" +
      "chStringType\022\t\n\005EXACT\020\000\022\t\n\005REGEX\020\001\"2\n\tVa" +
      "lueType\022\010\n\004TEXT\020\000\022\r\n\tPARAMETER\020\001\022\014\n\010VARI" +
      "ABLE\020\002B+\n\035com.tencent.polaris.client.pbB" +
      "\nModelProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_v1_Location_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_v1_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v1_Location_descriptor,
        new java.lang.String[] { "Region", "Zone", "Campus", });
    internal_static_v1_MatchString_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_v1_MatchString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v1_MatchString_descriptor,
        new java.lang.String[] { "Type", "Value", "ValueType", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
