// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcapi_discovery.proto

package com.tencent.polaris.client.pb;

public final class PolarisGRPCService {
  private PolarisGRPCService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027grpcapi_discovery.proto\022\002v1\032\014client.pr" +
      "oto\032\rservice.proto\032\rrequest.proto\032\016respo" +
      "nse.proto2\207\002\n\013PolarisGRPC\022*\n\014ReportClien" +
      "t\022\n.v1.Client\032\014.v1.Response\"\000\0220\n\020Registe" +
      "rInstance\022\014.v1.Instance\032\014.v1.Response\"\000\022" +
      "2\n\022DeregisterInstance\022\014.v1.Instance\032\014.v1" +
      ".Response\"\000\022;\n\010Discover\022\023.v1.DiscoverReq" +
      "uest\032\024.v1.DiscoverResponse\"\000(\0010\001\022)\n\tHear" +
      "tbeat\022\014.v1.Instance\032\014.v1.Response\"\000B3\n\035c" +
      "om.tencent.polaris.client.pbB\022PolarisGRP" +
      "CServiceb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tencent.polaris.client.pb.ClientProto.getDescriptor(),
          com.tencent.polaris.client.pb.ServiceProto.getDescriptor(),
          com.tencent.polaris.client.pb.RequestProto.getDescriptor(),
          com.tencent.polaris.client.pb.ResponseProto.getDescriptor(),
        });
    com.tencent.polaris.client.pb.ClientProto.getDescriptor();
    com.tencent.polaris.client.pb.ServiceProto.getDescriptor();
    com.tencent.polaris.client.pb.RequestProto.getDescriptor();
    com.tencent.polaris.client.pb.ResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
