// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.tencent.polaris.client.pb;

public final class RequestProto {
  private RequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DiscoverRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:v1.DiscoverRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.v1.DiscoverRequest.DiscoverRequestType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.v1.DiscoverRequest.DiscoverRequestType type = 1;</code>
     * @return The type.
     */
    com.tencent.polaris.client.pb.RequestProto.DiscoverRequest.DiscoverRequestType getType();

    /**
     * <code>.v1.Service service = 2;</code>
     * @return Whether the service field is set.
     */
    boolean hasService();
    /**
     * <code>.v1.Service service = 2;</code>
     * @return The service.
     */
    com.tencent.polaris.client.pb.ServiceProto.Service getService();
    /**
     * <code>.v1.Service service = 2;</code>
     */
    com.tencent.polaris.client.pb.ServiceProto.ServiceOrBuilder getServiceOrBuilder();
  }
  /**
   * Protobuf type {@code v1.DiscoverRequest}
   */
  public static final class DiscoverRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:v1.DiscoverRequest)
      DiscoverRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DiscoverRequest.newBuilder() to construct.
    private DiscoverRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DiscoverRequest() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DiscoverRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DiscoverRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              com.tencent.polaris.client.pb.ServiceProto.Service.Builder subBuilder = null;
              if (service_ != null) {
                subBuilder = service_.toBuilder();
              }
              service_ = input.readMessage(com.tencent.polaris.client.pb.ServiceProto.Service.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(service_);
                service_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.polaris.client.pb.RequestProto.internal_static_v1_DiscoverRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.polaris.client.pb.RequestProto.internal_static_v1_DiscoverRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.polaris.client.pb.RequestProto.DiscoverRequest.class, com.tencent.polaris.client.pb.RequestProto.DiscoverRequest.Builder.class);
    }

    /**
     * Protobuf enum {@code v1.DiscoverRequest.DiscoverRequestType}
     */
    public enum DiscoverRequestType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>INSTANCE = 1;</code>
       */
      INSTANCE(1),
      /**
       * <code>CLUSTER = 2;</code>
       */
      CLUSTER(2),
      /**
       * <code>ROUTING = 3;</code>
       */
      ROUTING(3),
      /**
       * <code>RATE_LIMIT = 4;</code>
       */
      RATE_LIMIT(4),
      /**
       * <code>CIRCUIT_BREAKER = 5;</code>
       */
      CIRCUIT_BREAKER(5),
      /**
       * <code>SERVICES = 6;</code>
       */
      SERVICES(6),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>INSTANCE = 1;</code>
       */
      public static final int INSTANCE_VALUE = 1;
      /**
       * <code>CLUSTER = 2;</code>
       */
      public static final int CLUSTER_VALUE = 2;
      /**
       * <code>ROUTING = 3;</code>
       */
      public static final int ROUTING_VALUE = 3;
      /**
       * <code>RATE_LIMIT = 4;</code>
       */
      public static final int RATE_LIMIT_VALUE = 4;
      /**
       * <code>CIRCUIT_BREAKER = 5;</code>
       */
      public static final int CIRCUIT_BREAKER_VALUE = 5;
      /**
       * <code>SERVICES = 6;</code>
       */
      public static final int SERVICES_VALUE = 6;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DiscoverRequestType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DiscoverRequestType forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return INSTANCE;
          case 2: return CLUSTER;
          case 3: return ROUTING;
          case 4: return RATE_LIMIT;
          case 5: return CIRCUIT_BREAKER;
          case 6: return SERVICES;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DiscoverRequestType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DiscoverRequestType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DiscoverRequestType>() {
              public DiscoverRequestType findValueByNumber(int number) {
                return DiscoverRequestType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tencent.polaris.client.pb.RequestProto.DiscoverRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final DiscoverRequestType[] VALUES = values();

      public static DiscoverRequestType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DiscoverRequestType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:v1.DiscoverRequest.DiscoverRequestType)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.v1.DiscoverRequest.DiscoverRequestType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.v1.DiscoverRequest.DiscoverRequestType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public com.tencent.polaris.client.pb.RequestProto.DiscoverRequest.DiscoverRequestType getType() {
      @SuppressWarnings("deprecation")
      com.tencent.polaris.client.pb.RequestProto.DiscoverRequest.DiscoverRequestType result = com.tencent.polaris.client.pb.RequestProto.DiscoverRequest.DiscoverRequestType.valueOf(type_);
      return result == null ? com.tencent.polaris.client.pb.RequestProto.DiscoverRequest.DiscoverRequestType.UNRECOGNIZED : result;
    }

    public static final int SERVICE_FIELD_NUMBER = 2;
    private com.tencent.polaris.client.pb.ServiceProto.Service service_;
    /**
     * <code>.v1.Service service = 2;</code>
     * @return Whether the service field is set.
     */
    @java.lang.Override
    public boolean hasService() {
      return service_ != null;
    }
    /**
     * <code>.v1.Service service = 2;</code>
     * @return The service.
     */
    @java.lang.Override
    public com.tencent.polaris.client.pb.ServiceProto.Service getService() {
      return service_ == null ? com.tencent.polaris.client.pb.ServiceProto.Service.getDefaultInstance() : service_;
    }
    /**
     * <code>.v1.Service service = 2;</code>
     */
    @java.lang.Override
    public com.tencent.polaris.client.pb.ServiceProto.ServiceOrBuilder getServiceOrBuilder() {
      return getService();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.tencent.polaris.client.pb.RequestProto.DiscoverRequest.DiscoverRequestType.UNKNOWN.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (service_ != null) {
        output.writeMessage(2, getService());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.tencent.polaris.client.pb.RequestProto.DiscoverRequest.DiscoverRequestType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (service_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getService());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tencent.polaris.client.pb.RequestProto.DiscoverRequest)) {
        return super.equals(obj);
      }
      com.tencent.polaris.client.pb.RequestProto.DiscoverRequest other = (com.tencent.polaris.client.pb.RequestProto.DiscoverRequest) obj;

      if (type_ != other.type_) return false;
      if (hasService() != other.hasService()) return false;
      if (hasService()) {
        if (!getService()
            .equals(other.getService())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasService()) {
        hash = (37 * hash) + SERVICE_FIELD_NUMBER;
        hash = (53 * hash) + getService().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tencent.polaris.client.pb.RequestProto.DiscoverRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.polaris.client.pb.RequestProto.DiscoverRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.polaris.client.pb.RequestProto.DiscoverRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.polaris.client.pb.RequestProto.DiscoverRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.polaris.client.pb.RequestProto.DiscoverRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tencent.polaris.client.pb.RequestProto.DiscoverRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tencent.polaris.client.pb.RequestProto.DiscoverRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.polaris.client.pb.RequestProto.DiscoverRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.polaris.client.pb.RequestProto.DiscoverRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tencent.polaris.client.pb.RequestProto.DiscoverRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tencent.polaris.client.pb.RequestProto.DiscoverRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tencent.polaris.client.pb.RequestProto.DiscoverRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tencent.polaris.client.pb.RequestProto.DiscoverRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code v1.DiscoverRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:v1.DiscoverRequest)
        com.tencent.polaris.client.pb.RequestProto.DiscoverRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tencent.polaris.client.pb.RequestProto.internal_static_v1_DiscoverRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tencent.polaris.client.pb.RequestProto.internal_static_v1_DiscoverRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tencent.polaris.client.pb.RequestProto.DiscoverRequest.class, com.tencent.polaris.client.pb.RequestProto.DiscoverRequest.Builder.class);
      }

      // Construct using com.tencent.polaris.client.pb.RequestProto.DiscoverRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        if (serviceBuilder_ == null) {
          service_ = null;
        } else {
          service_ = null;
          serviceBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tencent.polaris.client.pb.RequestProto.internal_static_v1_DiscoverRequest_descriptor;
      }

      @java.lang.Override
      public com.tencent.polaris.client.pb.RequestProto.DiscoverRequest getDefaultInstanceForType() {
        return com.tencent.polaris.client.pb.RequestProto.DiscoverRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.tencent.polaris.client.pb.RequestProto.DiscoverRequest build() {
        com.tencent.polaris.client.pb.RequestProto.DiscoverRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tencent.polaris.client.pb.RequestProto.DiscoverRequest buildPartial() {
        com.tencent.polaris.client.pb.RequestProto.DiscoverRequest result = new com.tencent.polaris.client.pb.RequestProto.DiscoverRequest(this);
        result.type_ = type_;
        if (serviceBuilder_ == null) {
          result.service_ = service_;
        } else {
          result.service_ = serviceBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tencent.polaris.client.pb.RequestProto.DiscoverRequest) {
          return mergeFrom((com.tencent.polaris.client.pb.RequestProto.DiscoverRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tencent.polaris.client.pb.RequestProto.DiscoverRequest other) {
        if (other == com.tencent.polaris.client.pb.RequestProto.DiscoverRequest.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasService()) {
          mergeService(other.getService());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tencent.polaris.client.pb.RequestProto.DiscoverRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tencent.polaris.client.pb.RequestProto.DiscoverRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.v1.DiscoverRequest.DiscoverRequestType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.v1.DiscoverRequest.DiscoverRequestType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.v1.DiscoverRequest.DiscoverRequestType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.tencent.polaris.client.pb.RequestProto.DiscoverRequest.DiscoverRequestType getType() {
        @SuppressWarnings("deprecation")
        com.tencent.polaris.client.pb.RequestProto.DiscoverRequest.DiscoverRequestType result = com.tencent.polaris.client.pb.RequestProto.DiscoverRequest.DiscoverRequestType.valueOf(type_);
        return result == null ? com.tencent.polaris.client.pb.RequestProto.DiscoverRequest.DiscoverRequestType.UNRECOGNIZED : result;
      }
      /**
       * <code>.v1.DiscoverRequest.DiscoverRequestType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.tencent.polaris.client.pb.RequestProto.DiscoverRequest.DiscoverRequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.v1.DiscoverRequest.DiscoverRequestType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.tencent.polaris.client.pb.ServiceProto.Service service_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tencent.polaris.client.pb.ServiceProto.Service, com.tencent.polaris.client.pb.ServiceProto.Service.Builder, com.tencent.polaris.client.pb.ServiceProto.ServiceOrBuilder> serviceBuilder_;
      /**
       * <code>.v1.Service service = 2;</code>
       * @return Whether the service field is set.
       */
      public boolean hasService() {
        return serviceBuilder_ != null || service_ != null;
      }
      /**
       * <code>.v1.Service service = 2;</code>
       * @return The service.
       */
      public com.tencent.polaris.client.pb.ServiceProto.Service getService() {
        if (serviceBuilder_ == null) {
          return service_ == null ? com.tencent.polaris.client.pb.ServiceProto.Service.getDefaultInstance() : service_;
        } else {
          return serviceBuilder_.getMessage();
        }
      }
      /**
       * <code>.v1.Service service = 2;</code>
       */
      public Builder setService(com.tencent.polaris.client.pb.ServiceProto.Service value) {
        if (serviceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          service_ = value;
          onChanged();
        } else {
          serviceBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.v1.Service service = 2;</code>
       */
      public Builder setService(
          com.tencent.polaris.client.pb.ServiceProto.Service.Builder builderForValue) {
        if (serviceBuilder_ == null) {
          service_ = builderForValue.build();
          onChanged();
        } else {
          serviceBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.v1.Service service = 2;</code>
       */
      public Builder mergeService(com.tencent.polaris.client.pb.ServiceProto.Service value) {
        if (serviceBuilder_ == null) {
          if (service_ != null) {
            service_ =
              com.tencent.polaris.client.pb.ServiceProto.Service.newBuilder(service_).mergeFrom(value).buildPartial();
          } else {
            service_ = value;
          }
          onChanged();
        } else {
          serviceBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.v1.Service service = 2;</code>
       */
      public Builder clearService() {
        if (serviceBuilder_ == null) {
          service_ = null;
          onChanged();
        } else {
          service_ = null;
          serviceBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.v1.Service service = 2;</code>
       */
      public com.tencent.polaris.client.pb.ServiceProto.Service.Builder getServiceBuilder() {
        
        onChanged();
        return getServiceFieldBuilder().getBuilder();
      }
      /**
       * <code>.v1.Service service = 2;</code>
       */
      public com.tencent.polaris.client.pb.ServiceProto.ServiceOrBuilder getServiceOrBuilder() {
        if (serviceBuilder_ != null) {
          return serviceBuilder_.getMessageOrBuilder();
        } else {
          return service_ == null ?
              com.tencent.polaris.client.pb.ServiceProto.Service.getDefaultInstance() : service_;
        }
      }
      /**
       * <code>.v1.Service service = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tencent.polaris.client.pb.ServiceProto.Service, com.tencent.polaris.client.pb.ServiceProto.Service.Builder, com.tencent.polaris.client.pb.ServiceProto.ServiceOrBuilder> 
          getServiceFieldBuilder() {
        if (serviceBuilder_ == null) {
          serviceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.tencent.polaris.client.pb.ServiceProto.Service, com.tencent.polaris.client.pb.ServiceProto.Service.Builder, com.tencent.polaris.client.pb.ServiceProto.ServiceOrBuilder>(
                  getService(),
                  getParentForChildren(),
                  isClean());
          service_ = null;
        }
        return serviceBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:v1.DiscoverRequest)
    }

    // @@protoc_insertion_point(class_scope:v1.DiscoverRequest)
    private static final com.tencent.polaris.client.pb.RequestProto.DiscoverRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tencent.polaris.client.pb.RequestProto.DiscoverRequest();
    }

    public static com.tencent.polaris.client.pb.RequestProto.DiscoverRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DiscoverRequest>
        PARSER = new com.google.protobuf.AbstractParser<DiscoverRequest>() {
      @java.lang.Override
      public DiscoverRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DiscoverRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DiscoverRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DiscoverRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tencent.polaris.client.pb.RequestProto.DiscoverRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_v1_DiscoverRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_v1_DiscoverRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rrequest.proto\022\002v1\032\rservice.proto\"\345\001\n\017D" +
      "iscoverRequest\0225\n\004type\030\001 \001(\0162\'.v1.Discov" +
      "erRequest.DiscoverRequestType\022\034\n\007service" +
      "\030\002 \001(\0132\013.v1.Service\"}\n\023DiscoverRequestTy" +
      "pe\022\013\n\007UNKNOWN\020\000\022\014\n\010INSTANCE\020\001\022\013\n\007CLUSTER" +
      "\020\002\022\013\n\007ROUTING\020\003\022\016\n\nRATE_LIMIT\020\004\022\023\n\017CIRCU" +
      "IT_BREAKER\020\005\022\014\n\010SERVICES\020\006B-\n\035com.tencen" +
      "t.polaris.client.pbB\014RequestProtob\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tencent.polaris.client.pb.ServiceProto.getDescriptor(),
        });
    internal_static_v1_DiscoverRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_v1_DiscoverRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_v1_DiscoverRequest_descriptor,
        new java.lang.String[] { "Type", "Service", });
    com.tencent.polaris.client.pb.ServiceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
