// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcapi_v2_metric.proto

package com.tencent.polaris.ratelimit.client.pb;

public final class GrpcapiV2Metric {
  private GrpcapiV2Metric() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027grpcapi_v2_metric.proto\022\021polaris.metri" +
      "c.v2\032\022ratelimit_v2.proto2\312\001\n\017RateLimitGR" +
      "PCV2\022Z\n\007Service\022#.polaris.metric.v2.Rate" +
      "LimitRequest\032$.polaris.metric.v2.RateLim" +
      "itResponse\"\000(\0010\001\022[\n\nTimeAdjust\022$.polaris" +
      ".metric.v2.TimeAdjustRequest\032%.polaris.m" +
      "etric.v2.TimeAdjustResponse\"\000B-\n\'com.ten" +
      "cent.polaris.ratelimit.client.pbZ\002v2b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tencent.polaris.ratelimit.client.pb.RatelimitV2.getDescriptor(),
        });
    com.tencent.polaris.ratelimit.client.pb.RatelimitV2.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
