name: integration test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        java: [ 8, 11, 17 ]
    name: integration test
    runs-on: ubuntu-latest
    services:
      polaris:
        image: polarismesh/polaris-standalone:latest
        ports:
          - 8090:8090
          - 8091:8091
          - 8093:8093
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn clean verify -DskipTests -B -U -Psonatype --file pom.xml
      - name: Integration test with Maven
        run: mvn failsafe:integration-test

