name: License checker

on:
  push:
    branches:
      - main
      - release/*
      - dev
  pull_request:
    branches:
      - main
      - release/*
      - dev
jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4
      - name: Check License Header
        uses: apache/skywalking-eyes@v0.4.0
